from .trainer import ImportancePruner, BaseImportancePruningTrainer
from .combinations import DepthImportancePruningTrainer
from .combinations import BaseImportancePrunerInDensifyTrainer, DepthImportancePrunerInDensifyTrainer
from .combinations import ImportancePruningTrainer
from .combinations import ImportancePrunerInDensifyTrainer
