from .trainer import ImportancePruner, BaseImportancePruningTrainer, ImportancePrunerWrapper
from .combinations import BaseImportancePrunerInDensifyTrainer, ImportancePruningTrainer, ImportancePrunerInDensifyTrainer
