from .combinations import FullPruningDensifierWrapper, FullPruningTrainerWrapper, BaseFullPruningTrainer, FullPruningTrainer
from .combinations import FullReducedDensificationDensifierWrapper, FullReducedDensificationTrainerWrapper, BaseFullReducedDensificationTrainer, FullReducedDensificationTrainer
from .combinations import OpacityResetFullReducedDensificationTrainer
from .combinations import SHCullingOpacityResetDensificationTrainer, SHCullingFullPruningTrainer, SHCullingFullReducedDensificationTrainer, SHCullingOpacityResetFullReducedDensificationTrainer
from .combinations import CameraSHCullingTrainer, CameraFullPruningTrainer, CameraFullReducedDensificationTrainer, CameraOpacityResetFullReducedDensificationTrainer
from .combinations import CameraSHCullingOpacityResetDensificationTrainer, CameraSHCullingFullPruningTrainer, CameraSHCullingOpacityResetFullReducedDensificationTrainer, CameraSHCullingOpacityResetFullReducedDensificationTrainer
