name: Python package for Windows

on:
  push:
    paths:
      - "setup.py"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel twine
      - name: Install pytorch
        run: pip install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu124
      - name: Setup CUDA
        uses: Jimver/cuda-toolkit@v0.2.19
        id: cuda-toolkit
        with:
          cuda: "12.4.1"
          method: "network"
          sub-packages: '["nvcc", "cudart"]'
      - name: Build package
        run: python setup.py bdist_wheel sdist
        env:
          TORCH_CUDA_ARCH_LIST: Turing
      - name: Publish release
        run: |
          python -m twine upload dist/* --username __token__ --password ${{ secrets.PIP_API_TOKEN }} --skip-existing
